[[MathGL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6558550c52ad222be6b9cc18c1afbcfbe619c04b"
libc = "glibc"
os = "linux"

    [[MathGL.download]]
    sha256 = "4188fb025901a8e1493bbc92bab4ab1f657274ec0dd0f461a5c2f12df70c17a3"
    url = "https://github.com/JuliaBinaryWrappers/MathGL_jll.jl/releases/download/MathGL-v2.4.4+1/MathGL.v2.4.4.x86_64-linux-gnu-cxx03.tar.gz"
[[MathGL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0f3e667b9b3da831953f4018807d8e29b916ece"
libc = "glibc"
os = "linux"

    [[MathGL.download]]
    sha256 = "e0d2d48193ac6a70be9bcb2099431ad1ddd30fcbf1d92d0eb66b4455b4b6cbe5"
    url = "https://github.com/JuliaBinaryWrappers/MathGL_jll.jl/releases/download/MathGL-v2.4.4+1/MathGL.v2.4.4.x86_64-linux-gnu-cxx11.tar.gz"
[[MathGL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "580568335770afaefe48688aec2ac7d2e7b47d17"
os = "windows"

    [[MathGL.download]]
    sha256 = "4a6adb9c74a4a58832515b010e98f30c977668c332b55a2d787d550ef332868e"
    url = "https://github.com/JuliaBinaryWrappers/MathGL_jll.jl/releases/download/MathGL-v2.4.4+1/MathGL.v2.4.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[MathGL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47dbe420c2ab097dfa9bc953d8c083f9246752c5"
os = "windows"

    [[MathGL.download]]
    sha256 = "9af49f679e3be2ddbe671e3585a80d2cffa19c8fb0420ba25e9eb3b45ad909fd"
    url = "https://github.com/JuliaBinaryWrappers/MathGL_jll.jl/releases/download/MathGL-v2.4.4+1/MathGL.v2.4.4.x86_64-w64-mingw32-cxx11.tar.gz"
